name: Deploy

on:
  push:
#    branches:
#      - releases
  workflow_dispatch:

jobs:

  deploy:

    runs-on: "ubuntu-latest"

    steps:
      - name: get version from commit message
        id: get-version
        run: |
          echo "::set-output name=result::$(echo ${{ github.event.head_commit.message }} | sed 's/^v//)"

      - name: download library as artifact
        uses: actions/download-artifact@v2
        with:
          name: consigliere-${{ steps.get-version.outputs.result }}
          path: dist/

#      - name: upload library to pypi
#        if: startsWith(github.ref, 'refs/tags')
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_TOKEN }}
#          verbose: true
